Add: AIT 論文追加
lapsquash/lapsquash_pj pull request #7
Opened 2023-10-19 01:04 UTC by knee0expert

2023-10-19 01:09 UTC, tomoakinakayama commented on docs/AIT/article/work.md
> +動物園の動物は夜行性も多く、動いていないことが多い。普段どのような行動をしているのか映像で確認できれば子どもたちも喜ぶのではないか。
コメント

2023-10-19 01:09 UTC, tomoakinakayama commented on docs/AIT/article/work.md
> +動物園へ行った際、 見に行った動物が動いていなくて寂しい思いをした経験があると思う。この問題を解決するためには, 動物の様子を定点カメラ等で長時間撮影し, 動いている場面を確認する方法があるが, 長時間撮影された動画を全て見ることは困難である。そのため, 長時間の動画を分析・分類をし, 動画から特徴的な行動の部分のみを抽出できるアプリを作成しようと考えた。抽出した動画に説明を付けて, PC アプ
```suggestion
動物園へ行った際、見に行った動物が動いていなくて寂しい思いをした経験があると思う。この問題を解決するためには, 動物の様子を定点カメラ等で長時間撮影し, 動いている場面を確認する方法があるが, 長時間撮影された動画を全て見ることは困難である。そのため, 長時間の動画を分析・分類をし, 動画から特徴的な行動の部分のみを抽出できるアプリを作成しようと考えた。抽出した動画に説明を付けて, PC アプリ上に表示させることで, 動物たちが何を考えて行動しているのかの理解を深められると考えた。しかし、手動で分析・分類をするのは現実的ではない。そこで小型コンピュータである Raspberrt Pi を使用した。GPT-4 の API を利用し、AI に学習させて分析・分類を行うことにした。
```


余分なスペースが含まれているので消す

2023-10-25 08:16 UTC, wappon28dev requested changes
とりあえずざっと見たところだけレビューしました！！！  
まだ完成度が足りなさそうなので, また更新されたらじっくり中を見たいと思います！

頑張ろう :fire:

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +1 フレームごとに類似度ハッシュ算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法で近似し、 その傾きを求める。　
余分なスペースが含まれてるかもです.

```suggestion
1 フレームごとに類似度ハッシュ算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法で近似し、 その傾きを求める。
```

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +これら（分析したデータ？)のファイルをオブジェクトストレージである SharePoint に保存する。
[`shared/docs/2_IEE/work/slide.pptx`](https://tiny.cc/lapsq-sh/docs/2_IEE/work/slide.pptx?web=1) の 23 枚目の文言に揃えてみると以下のようになるかな.

```suggestion
ビデオクリップとタイル画像、メタデータをひとまとめにしたファイルをオブジェクトストレージである SharePoint に保存する。
```

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +近年、技術の発達によって、研究機関や家庭、学校でも長時間動画を撮影する機会が増えた。しかし、長時間の動画の確認をすることは非常に非効率であるため、自動的に場面を抽出できるシステムを開発した。抽出した動画に説明を付けて、 PC アプリ上に表示することができる。今回は動物を対象に設定した。動物の場合、何を考えて行動しているのかの理解を深められると考えた。この研究を応用して、中学生までの子供を対象に動
Viewer は Web アプリになった ([Teams](https://teams.microsoft.com/l/message/19:1TXRoaYLNGTCCO6o2jpRhEF2SIHngSZx21uq7BbUnxI1@thread.tacv2/1696464569569?tenantId=8a072654-87e2-4c68-838b-e198e6a11cf2&groupId=1d529e0c-38ed-4537-8945-25ee87b5a0d8&parentMessageId=1696464569569&teamName=lapsquash_teachers&channelName=General&createdTime=1696464569569)) なので, “PC アプリ” ではなく “Web アプリ” になるかと……！

```suggestion
近年、技術の発達によって、研究機関や家庭、学校でも長時間動画を撮影する機会が増えた。しかし、長時間の動画の確認をすることは非常に非効率であるため、自動的に場面を抽出できるシステムを開発した。抽出した動画に説明を付けて、 Web アプリ上に表示することができる。今回は動物を対象に設定した。動物の場合、何を考えて行動しているのかの理解を深められると考えた。この研究を応用して、中学生までの子供を対象に動物園の事前学習に応用に利用でき、動物行動の研究だけではなく、幅広い分野の分析・分類や監視カメラとしての活用も期待できると考える。
```

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動物園の業務の中に「動物の檻の中で撮影した動画を見てノートを書く」というものがあるらしく、２、３時間必要だと聞いたため、業務の負担を軽減すること、
数値などの範囲を結ぶときは `–` (en dash) を使おう！

```suggestion
動物園の業務の中に「動物の檻の中で撮影した動画を見てノートを書く」というものがあるらしく、2–3 時間必要だと聞いたため、業務の負担を軽減すること、
```

ref:  
- [エヌダッシュ：範囲はまっすぐ示す - SpecAid](https://specaid.net/basics/en-dash-for-range.html)

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +システムは、撮影に Raspberry Pi、動画分析には GPT-4 の API を利用した。 長時間の動画から自動的に活動シーンだけを切り抜き、AI を用いて分析・分類しアプリとして表示する。
GPT-4 → Bard かな.

https://github.com/lapsquash/lapsquash_pj/blob/59342d7db563afd662243b2782ca84ef01722894/docs/IEE.md?plain=1#L124-L128

```suggestion
システムは、撮影に Raspberry Pi、動画分析には Bard の Image Input API を利用した。 長時間の動画から自動的に活動シーンだけを切り抜き、AI を用いて分析・分類しアプリとして表示する。
```

2023-10-25 08:16 UTC, wappon28dev commented on docs/AIT/article/work.md
> +)
現在まとめ中なので, 後にこのブランチにコミット積むねー

2023-10-25 08:16 UTC, wappon28dev commented on docs/midterm.md
> +https://prod.liveshare.vsengsaas.visualstudio.com/join?9A14F50ED026BA9D4E30D5F6F3EA551F70B0
これはミスかな？

```suggestion
squasher は Raspberry Pi 上で動いており, viewer は好きな PC で動きます.  
しかし, analyzer はエッジ関数として, 世界中のどこからでも実行できるようになっています.  
1 つ工夫点は, エッジ関数としての analyzer のコードが git submodule として, 他の squasher や viewer のコードに組み込まれていることです.  
この理由は analyzer の API を tRPC で記述することによって, 他のどちらからでも型安全に呼び出せるようにするためです.
```

2023-10-25 23:47 UTC, knee0expert commented on docs/AIT/article/work.md
> +1 フレームごとに類似度ハッシュ算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法で近似し、 その傾きを求める。　
直したよ

2023-10-25 23:47 UTC, knee0expert commented on docs/AIT/article/work.md
> +これら（分析したデータ？)のファイルをオブジェクトストレージである SharePoint に保存する。
直したよー

2023-10-25 23:47 UTC, knee0expert commented on docs/AIT/article/work.md
> +近年、技術の発達によって、研究機関や家庭、学校でも長時間動画を撮影する機会が増えた。しかし、長時間の動画の確認をすることは非常に非効率であるため、自動的に場面を抽出できるシステムを開発した。抽出した動画に説明を付けて、 PC アプリ上に表示することができる。今回は動物を対象に設定した。動物の場合、何を考えて行動しているのかの理解を深められると考えた。この研究を応用して、中学生までの子供を対象に動
直したよー

2023-10-25 23:47 UTC, knee0expert commented on docs/AIT/article/work.md
> +動物園の業務の中に「動物の檻の中で撮影した動画を見てノートを書く」というものがあるらしく、２、３時間必要だと聞いたため、業務の負担を軽減すること、
了解です

2023-10-25 23:48 UTC, knee0expert commented on docs/AIT/article/work.md
> +システムは、撮影に Raspberry Pi、動画分析には GPT-4 の API を利用した。 長時間の動画から自動的に活動シーンだけを切り抜き、AI を用いて分析・分類しアプリとして表示する。
ok

2023-10-25 23:48 UTC, knee0expert commented on docs/AIT/article/work.md
> +)
お願いしますー

2023-11-01 09:09 UTC, wappon28dev requested changes
なる早 (ガチ) で直そう！！！

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +1 つ目は類似度ハッシュを利用して検出する方法。類似度ハッシュは、 画像の特徴を抽出してハッシュ値に変換する関数であり、
基本的に論文では, 体言止めを避けよう.

```suggestion
1 つ目は類似度ハッシュを利用して検出する方法である。類似度ハッシュは、 画像の特徴を抽出してハッシュ値に変換する関数であり、
```

ref: 
- [論文やレポートには、体言止めは使用しない！ - 日本の大学・大学院へ行こう！](https://ameblo.jp/nihongokyoshijapan/entry-12624401843.html)
- [論文の書き方と留意事項 - KOJIMA SEMINAR](http://www2.ngu.ac.jp/~kkojima/seminar/ronbun.html#:~:text=%E9%80%A3%E7%B5%A1%E6%96%87%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84%E3%81%AE%E3%81%A7%E3%80%81%E4%BD%93%E8%A8%80%E6%AD%A2%E3%82%81%E3%81%AF%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84%E3%80%82)

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +同じ画像であれば値は一致し、 違う画像であれば輝度や色、 輪郭の変化によって少しずつ変化する。s0、s1 のように画像が変化した場合も検出できる。
どの $s0$, $s1$ かが分からないかも.

```suggestion
同じ画像であれば値は一致し、 違う画像であれば輝度や色、 輪郭の変化によって少しずつ変化する。図 3 の s0、s1 のように画像が変化した場合も検出できる。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +しかし、 s1、s2 のように画像の背景のみが変化した場合でもハッシュが変化してしまうため、
背景が変化したときの図が挿入されていないので, この文は意味を成していない.  
さしあたって, 背景が変化したときの図を追加で必要かな？

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +図から、 レンダラーもモデルもイベントループを継承している。
図表番号がズレているかも.

```suggestion
図 4 から、 レンダラーもモデルもイベントループを継承している。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +1 フレームごとに類似度ハッシュ算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法　最小二乗法（または、最小自乗法）とは、誤差を伴う測定値の処理において、その誤差の二乗の和を最小にすることで、最も確からしい関係式を求める方法。で近似し、 その傾きを求める。
助詞の “が” が抜けている.  また, 最小二乗法の説明は読者層より必要ないかも. 

```suggestion
1 フレームごとに類似度ハッシュが算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法で 1 次式で近似し、その傾きを求める。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +開発当初は決めたしきい値で切り抜きを行っていたが、 動画によって最適なしきい値が異なるため、 過去の傾きから指数移動平均を取って動的な切り抜きを始める方法に変更した。
- 静的 ↔ 動的 なので, その用語に揃える.
- “動的な切り抜き” は前後に無い言葉なので, “切り抜きを行う” に揃える.

```suggestion
開発当初は静的なしきい値で切り抜きを行っていたが、動画によって最適なしきい値が異なるため、過去の傾きから指数移動平均を取って動的なしきい値を使った切り抜きを行う方法に変更した。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動画のタイル化・圧縮を行った。 AI のインプット用にビデオクリップから時間ごとのタイル画像を生成する。これにより、 画像入力ができる Bard が解析可能になる。
Bard は解析される側ではなく, 解析する側である.

```suggestion
動画のタイル化・圧縮を行った。 AI のインプット用にビデオクリップから時間ごとのタイル画像を生成する。これにより、 画像入力ができる Bard で解析可能になる。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +ビデオクリップとタイル画像、メタデータをひとまとめにしたファイルをオブジェクトストレージである SharePoint に保存する。
接続詞がなく, ちょっと文同士のつながりが不自然かも.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +SharePoint は、 Graph API という API エンドポイント経由でアクセスが可能。OAuth 2.0 に準拠するように実装したため、 ユーザーが squasher や viewer にアクセス権限の委任をすることで、 離れたところでも安全にデータを保存が可能になっている。
https://github.com/lapsquash/lapsquash_pj/pull/7#discussion_r1378515141 と一緒.
```suggestion
SharePoint は、 Graph API という API エンドポイント経由でアクセスが可能である。OAuth 2.0 に準拠するように実装したため、ユーザーが squasher や viewer にアクセス権限の委任をすることで、 離れたところでも安全にデータを保存が可能になっている。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +viewer では lapsquash ファイルを読み込み、動画を閲覧可能。 また、AI が生成した説明やタグを一緒に確認することにより、動物が何をしているのか、また、その行動の意味が分かりやすくなっている。
https://github.com/lapsquash/lapsquash_pj/pull/7#discussion_r1378515141 と一緒.

```suggestion
viewer では lapsquash ファイルを読み込み、動画を閲覧可能である。 また、AI が生成した説明やタグを一緒に確認することにより、動物が何をしているのか、また、その行動の意味が分かりやすくなっている。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +Material Design を採用することで、デバイスの画面サイズに合わせてデザインを最適化しやすいように装飾を減らし、シンプルなデザインを基本としている。そのため、別のデバイスで使用する時でも操作が容易となっている。それに加え ニューモフィズム デザインを採用することで Material Design のシンプルさに加え UX の向上を図った。ニューモフィズムとは Material Des
- 余分なスペース

> ニューモフィズムとは Material Design のようなフラットデザインに……

Material Design はフラットデザインではないので, この記述は不正確かも.


```suggestion
Material Design を採用することで、デバイスの画面サイズに合わせてデザインを最適化しやすいように装飾を減らし、シンプルなデザインを基本としている。そのため、別のデバイスで使用する時でも操作が容易となっている。それに加えニューモフィズムデザインを採用することで Material Design のシンプルさに加え UX の向上を図った。ニューモフィズムとは Material Design のようなフラットデザインに凹凸を加えたデザインのことである。これを採用することで操作性の向上や他のアプリとの UI での差別化をした。
```

refs:
- [歴史から考えるフラットデザインとマテリアルデザインの違いとは？ - MX MILK](https://uxmilk.jp/55997)
- [フラットデザインとは？マテリアルデザインとは何が違う？ - ferret](https://ferret-plus.com/11978)

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +viewer のデザインについて。 Material Design を一部採用し、 ニューモフィズムと丸みを持たせたデザインにすることによって操作しやすく、 親しみやすいアプリにした。 また、インタラクティブな UI にすることでパソコン操作が苦手な人でも直感的な操作が可能になっている。
> viewer のデザインについて。

ここが話し言葉かも.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +次に画面の構成について。 この画面では、動物ごとのダイジェストを確認することが可能となっている。
https://github.com/lapsquash/lapsquash_pj/pull/7#discussion_r1378528778 と一緒.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +squasher は Raspberry Pi 上で動いており、 viewer は好きな デバイス で動く。
余分なスペース.

```suggestion
squasher は Raspberry Pi 上で動いており、 viewer は好きなデバイスで動く。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +工夫点としては, エッジ関数としての analyzer のコードが git submodule として, 他の squasher や viewer のコードに組み込まれていることだ。 analyzer の API を tRPC で記述することによって, 他のどちらからでも型安全に呼び出すことができる。
- 冗長な記述を削除
- `, ` と `、` が混ざっているので統一
- `だ` → `である` に統一

```suggestion
工夫点は、エッジ関数としての analyzer のコードが git submodule として、他の squasher や viewer のコードに組み込まれていることである。 analyzer の API を tRPC で記述することによって, 他のどちらからでも型安全に呼び出すことができる。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +研究期間中は、 カメラモジュールからの動画を Raspberry Pi を使用して対象の動物が動いている場面のみを抽出、細分化して圧縮し、 アップロードを行い、 動画を Bard の Image Input API で分析する。また、 分析結果と共にストレージへ保存し、 lapsquash アプリで AI が生成した説明の文章とともに表示される。
> 研究期間中は、

ここの文章は研究計画書で書いたこと (= どんな研究を行う予定かを書いたこと) だから, 研究でやったことを書くと良いかも.
つまり, 前の文章に合わせて過去形にすると良いかも.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +10 月 22 日に東山動物園の飼育員さんに話を聞いた際、動物行動の定義付けに関する難しさを指摘いただいた。どんな動きをしたら"採食"なのか、餌を探しているとき、咀嚼中は"採食"みなされるのか。"喧嘩"と"遊び"、"睡眠"と"座る"の区別をどのように行うのか。
他の文章に合わせて, `“”` → `「」` に統一しよう.

```suggestion
10 月 22 日に東山動物園の飼育員さんに話を聞いた際、動物行動の定義付けに関する難しさを指摘いただいた。どんな動きをしたら「採食」なのか、餌を探しているとき、咀嚼中は「採食」みなされるのか。「喧嘩」と「遊び」、「睡眠」と「座る」の区別をどのように行うのか。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +現在の目的だと、"飼育員さんの業務の効率化"とずれてしまっている。
`現在の` の部分を短くて良いから, 具体的に書いてみよう.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +飼育員さんが必要としているのは１つのカメラでは全ての視野を補うのは難しいので、複数のカメラの映像を分析・分類すること。映像のズーム、ズームアウト機能。
ここの文章あたり文体あたりで要修正かも.

```suggestion
飼育員さんが必要としているのは１つのカメラでは全ての視野を補うのは難しいので、複数のカメラの映像を分析・分類すること。映像のズーム、ズームアウト機能。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +小さな対象に対しての切り抜き精度の向上、音声の分析・分類機能。(前述した"喧嘩"と"遊び"、"睡眠"と"座る"の区別をするため。行動によって声の出し方が異なる。)
https://github.com/lapsquash/lapsquash_pj/pull/7#discussion_r1378535895 と一緒.

```suggestion
小さな対象に対しての切り抜き精度の向上、音声の分析・分類機能。(前述した「喧嘩」と「遊び」、「睡眠」と「座る」の区別をするため。行動によって声の出し方が異なる。)
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +１つのアプリケーションで複数の動物っていうのはかなり難しい。解析にも課題がある。
全角 → 半角

```suggestion
1 つのアプリケーションで複数の動物っていうのはかなり難しい。解析にも課題がある。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +その動物にしか聞こえないような音域や、超音波、紫外線、赤外線などの人間には検知できないようなものもあるのでそれにも対応できれば動物だけでなく、昆虫にも使えて新たな発見があるかも。
“かも”……？

```suggestion
その動物にしか聞こえないような音域や、超音波、紫外線、赤外線などの人間には検知できないようなものもあるのでそれにも対応できれば動物だけでなく、昆虫にも使えて新たな発見があるかも。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +長い中で、これをピックアップするような作業っていうのがそもそも必要はない。
前後の文脈が読みづらいけど, “っていうのが” は話し言葉.

```suggestion
長い中で、これをピックアップするような作業はそもそも必要ない。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +担当者にしか見せない姿もあるが、逆に担当者には見せない姿もあったりする。0,,,.,00.そういうのを知ることができるから思わぬ発見もできる。
ここあたりの話し言葉を直すこと.

```suggestion
担当者にしか見せない姿もあるが、逆に担当者には見せない姿もある。そういうのを知ることができるから思わぬ発見もできる。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +勝手に動物に餌をやる人の検出など監視システムとしての利用方法
ここも Word で繋げるとおかしくなる.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +カメラの台数は増やして欲しい。
ここも書き言葉にすること.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +しかし、基本的に上から取った映像だけになってしまうため、２つの視点で　 AI に学習させれば時間短縮になるらしい。
- 余分なスペース削除.
- `上から` というのが情報不足かも.  画角の話をしていることがわかるようにしてみよう.
- `らしい` も表現を改めよう.

```suggestion
しかし、基本的に上から取った映像だけになってしまうため、２つの視点で AI に学習させれば時間短縮になるらしい。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +いろいろ詰め込みすぎた。
！？

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +１方向の動画のみで判断するのではなく、上からの映像と横からの映像と２方向の映像を使うとより精度が上がる。
https://github.com/lapsquash/lapsquash_pj/pull/7#discussion_r1378538606 と一緒.

```suggestion
1 方向の動画のみで判断するのではなく、上からの映像と横からの映像と 2 方向の映像を使うとより精度が上がる。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +来場者目線なら昨日までの 1 週間の平均で、最近はこの時間帯によく動くというのがデータとして分かるなら、来場者は目的の動物が動いている時間だけを観に行けて、動いていない時間は他の動物を見ることができる。動物が行動するタイミングを待たなくても良くなるため、動物園を回る効率が上がる。
漢字を修正

```suggestion
来場者目線なら昨日までの 1 週間の平均で、最近はこの時間帯によく動くというのがデータとして分かるなら、来場者は目的の動物が動いている時間だけを観に行けて、動いていない時間は他の動物を見ることができる。動物が行動するタイミングを待たなくても良くなるため、動物園を周る効率が上がる。
```

- [「回る」「周る」「廻る」の違いと意味とは？観光で店をまわる時は？ - スッキリ](https://gimon-sukkiri.jp/round_around/)
- [「回る」「周る」「廻る」の違いとは？ それぞれの意味と使い方を解説 - RUN-WAY](https://run-way.jp/lifestyle/term/mawaru/)

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +1 日の流れの中の何％をその行動に費やしてるかの割合を調べるのが行動観察だと多い。
話し言葉かな～～～.

```suggestion
1 日の流れの中の何％をその行動に費やしてるかの割合を調べることが行動観察だと多い。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +繁殖に関連するなら、回数になる。発情兆候が 1 日のうちに何回確認できたか。
ここも話し言葉かな～～～.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動物の出産後、担当者でもその様子を覗きにいくのはシビアで、最悪親が「ここは子育ての環境にない」してしまい、育児を放棄してしまう可能性がある。放棄してしまうと人工保育になる。人口で育てた子どもよりも親が育てた子どもの方が丈夫であるため、育児放棄の可能性を減らすため、カメラでできるだけ沢山の情報を取る必要がある。子どもの数、授乳の回数や音などを拾うことができれば、子どものさまざまなリスクは下げること
> 最悪親が「ここは子育ての環境にない」してしまい

ここの表現を直してみよう.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動物園の環境エンリッチメントの文献は見た方がいい。
！？

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +タグ自体は他の動物にも応用できるが、行動の中身は全然違う。
ここもしっかり書き言葉でまとめよう.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +この研究が実用化レベルであるなら導入したい
- 文末に `。` を追加
- 誰に対して `したい` なのか明確にしよう

```suggestion
この研究が実用化レベルであるなら導入したい。
```

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動物園の職員の方々の話を聞いた際、画面の動きだけでなく、音の分析・分類ができると動物の観察に役立つと聞いた。音の分析についてはあまり重要性を感じなかったが、動物の鳴き声は種類、性別、年齢時期などで鳴き方や声色が変わるとのこと。
> 動物の鳴き声は種類、性別、年齢時期などで鳴き方や声色が変わるとのこと。

ここも書き言葉にしよう.

2023-11-01 09:09 UTC, wappon28dev commented on docs/AIT/article/work.md
> +現状, 切り抜き範囲が細かすぎるなどの問題や, 実際に AI に説明させてみたところ, 抽象的な説明しかできなかった。
- `, ` → `、` に統一
- どんな風に “抽象的” だったのかを具体的に書いてみよう

```suggestion
現状、切り抜き範囲が細かすぎるなどの問題や、実際に AI に説明させてみたところ、抽象的な説明しかできなかった。  
```

2023-11-01 09:38 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +Material Design を採用することで、デバイスの画面サイズに合わせてデザインを最適化しやすいように装飾を減らし、シンプルなデザインを基本としている。そのため、別のデバイスで使用する時でも操作が容易となっている。それに加え ニューモフィズム デザインを採用することで Material Design のシンプルさに加え UX の向上を図った。ニューモフィズムとは Material Des
Material Design を削除して帳尻合わせ

2023-11-01 23:56 UTC, wappon28dev commented on docs/AIT/article/work.md
> +行動観察の場合、 1 日の流れの中の何％をその行動に費やしてるかの割合を調べることが多く、
“い” 抜き言葉

```suggestion
行動観察の場合、 1 日の流れの中の何％をその行動に費やしているかの割合を調べることが多く、
```

2023-11-02 00:08 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +過去に撮りためたビデオデータをその中から行動を切り抜く場合はこのままでも使うことができるが、リアルタイムだとまだ足りない部分がある。
"ビデオデータをその中から行動を切り抜く場合"日本語が変

```suggestion
過去に撮りためたビデオデータをその中から行動を切り抜く場合はこのままでも使うことができるが、リアルタイムだとまだ足りない部分がある。
```

2023-11-02 00:22 UTC, wappon28dev commented on docs/AIT/article/work.md
> +この図はプログラムの設計を表している。レンダラーとモデルが事前に定義したインターフェースを継承して実装した。
図が連続するので, 図表番号を入れたほうが良いかも.

```suggestion
図 3 はプログラムの設計を表している。レンダラーとモデルが事前に定義したインターフェースを継承して実装した。
```

2023-11-02 00:26 UTC, wappon28dev commented on docs/AIT/article/work.md
> +これらの設計の工夫によって、 リアルタイム性に優れた OpenCV や PyQtGraph, PySide などの適切なフレームワークを組み合わせて表示できた。
`,` → `、`


```suggestion
これらの設計の工夫によって、 リアルタイム性に優れた OpenCV や PyQtGraph、PySide などの適切なフレームワークを組み合わせて表示できた。
```

2023-11-02 00:26 UTC, wappon28dev commented on docs/AIT/article/work.md
> +1 フレームごとに類似度ハッシュが算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法で 1 次式で近似し、その傾きを求める。
`で` が続くので, `を使って～` で繋げたほうが良いかも by Word

```suggestion
1 フレームごとに類似度ハッシュが算出される。 類似度ハッシュの変化を知るために過去 1 秒の類似度ハッシュの値を最小二乗法を使って 1 次式で近似し、その傾きを求める。
```

2023-11-02 00:27 UTC, wappon28dev commented on docs/AIT/article/work.md
> +動画の切り抜き範囲を決めるアルゴリズム
この行はなんですか……？

2023-11-02 00:28 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +1 つの動物で複数の定点カメラがある場合を想定していなかった。
前の文章との繋がりがない

```suggestion
1 つの動物で複数の定点カメラがある場合を想定していなかった。
```

2023-11-02 00:31 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +その動物にしか聞こえないような音域や、超音波、紫外線、赤外線など人間には検知できない物にも対応させることができたら、動物だけでなく、昆虫など他の分野にも応用させられる可能性がある。
昆虫は動物の中に含まれてるため、"他の分野"とは言えないかも

```suggestion
その動物にしか聞こえないような音域や、超音波、紫外線、赤外線など人間には検知できない物にも対応させることができたら、動物だけでなく、昆虫など他の分野にも応用させられる可能性がある。
```

2023-11-02 00:40 UTC, wappon28dev commented on docs/AIT/article/work.md
> +本研究では Raspberry Pi で対象の動物が動いている場面のみを抽出し、ストレージに保存。抽出した場面に AI で説明と対応するタグをつける。将来の目的としては動物に対する知識を得るアプリとしての確立、動物行動以外の分野での応用を目的としている。
体言止め

```suggestion
本研究では Raspberry Pi で対象の動物が動いている場面のみを抽出し、ストレージに保存する。抽出した場面に AI で説明と対応するタグをつける。将来の目的としては動物に対する知識を得るアプリとしての確立、動物行動以外の分野での応用を目的としている。
```

2023-11-02 01:40 UTC, wappon28dev commented on docs/AIT/article/work.md
> +しかし、 s1、s2 のように画像の背景のみが変化した場合でもハッシュが変化してしまうため、
図は, レイアウトとモノクロに対応できない点で, 挿入できそうにないので文章を変更しよう.

```suggestion
しかし、画像の背景のみが変化した場合、対象物が動いていなくてもハッシュが変化してしまうため、
```

2023-11-02 01:41 UTC, wappon28dev commented on docs/AIT/article/work.md
> +研究期間中は、 カメラモジュールからの動画を Raspberry Pi を使用して対象の動物が動いている場面のみを抽出して Web アプリ状に表示した。 動画を Bard の Image Input API で分析し、分析結果と共にストレージへ保存し、 lapsquash アプリで AI が生成した説明の文章とともに表示される。
typo

```suggestion
研究期間中は、 カメラモジュールからの動画を Raspberry Pi を使用して対象の動物が動いている場面のみを抽出して Web アプリ上に表示した。 動画を Bard の Image Input API で分析し、分析結果と共にストレージへ保存し、 lapsquash アプリで AI が生成した説明の文章とともに表示される。
```

2023-11-02 06:42 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +分類した動画を事前に私たちが設定したタグに分類し、抽出した動画が何を写しているのか一目でわかるようになっている。 AI を用いて行動についての説明も追加し、学習にも役立つアプリとした。
どのようにしてタグを設定したのかの説明を追加

```suggestion
分類した動画を事前に私たちが設定したタグに分類し、抽出した動画が何を写しているのか一目でわかるようになっている。 AI を用いて行動についての説明も追加し、学習にも役立つアプリとした。
```

2023-11-02 07:43 UTC, wappon28dev commented on docs/AIT/article/work.md
> +また、 今学期にチームで分かりやすく全体図を制作した。(図 7)
> 今学期

は違う文言に直したほうが良いかも

2023-11-02 08:04 UTC, ROTO0504 commented on docs/AIT/article/work.md
> +動物行動の研究では必ずしも「動いている場面」ばかりを切り抜くわけではなく、見る目的によっては「動いていない場面」を切り抜く必要がある。また、担当者にしか見せない姿もあるが、過去に撮りためた動画から動物を観察することにより、担当者には見せない姿や、担当者が気付かなかったことを観察
文章途切れてる

```suggestion
動物行動の研究では必ずしも「動いている場面」ばかりを切り抜くわけではなく、見る目的によっては「動いていない場面」を切り抜く必要がある。また、担当者にしか見せない姿もあるが、過去に撮りためた動画から動物を観察することにより、担当者には見せない姿や、担当者が気付かなかったことを観察
```

2023-11-03 07:14 UTC, wappon28dev approved these changes
![image](https://github.com/lapsquash/lapsquash_pj/assets/86721991/ccb34e23-0294-4725-89b9-b41e1a2a7d54)

2023-11-03 07:20 UTC, tomoakinakayama approved these changes
OK

2023-11-04 13:15 UTC, merged